### ISSUE TITLE
Not sending error to elastic

### ISSUE THREAD

**Issue by aladin-tsi** [ssi-anik/elastic-apm-php#4]
Hello,

I am trying to use the package with laravel 6 but i got this error:

`"Call to undefined method Elastic\\Apm\\Impl\\Span::setLabel()","trace":"#0 \/var\/www\/html\/vendor\/anik\/elastic-apm-php\/src\/Agent.php(82): Anik\\ElasticApm\\Agent->includeSpansToTransaction(Object(Elastic\\Apm\\Impl\\Transaction), Object(Anik\\ElasticApm\\Spans\\QuerySpan))\n#1 \/var\/www\/html\/vendor\/anik\/elastic-apm-php\/src\/Middleware\/RecordForegroundTransaction.php(95): Anik\\ElasticApm\\Agent->capture()\n#2 \/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(212): Anik\\ElasticApm\\Middleware\\RecordForegroundTransaction->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))\n#3 \/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))\n#4 \/var\/www\/html\/public\/index.php(62): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))\n#5 {main}"

I need your help to show errors on my kibana apm dashboard`

Thanks,

**Comment by ssi-anik** [comment]
I didn't use the package since release. I hopefully will try to update the package this weekend. I guess there is a breaking change in the elastic apm PHP agent. As it's not stable.

**Comment by graemlourens** [comment]
@aladin-tsi it is an issue with the latest v1.0.0-beta1 from elastic.

PR submitted: https://github.com/ssi-anik/elastic-apm-php/pull/5

**Comment by biswajit-landmarkgroup** [comment]
@graemlourens , @aladin-tsi , Are you both able to send the errors to Elastic APM?

**Comment by graemlourens** [comment]
@aladin-tsi yes, with my branch it was working when i was experiementing with it a while ago: https://github.com/graemlourens/elastic-apm-php havn't touched it since February, so not sure
